user_pref("browser.aboutConfig.showWarning", false);
user_pref("devtools.chrome.enabled", true);
user_pref("devtools.debugger.remote-enabled", true);
user_pref("extensions.activeThemeID", "miniFox@t0ast.cc");
user_pref("extensions.torlauncher.prompt_at_startup", false);
user_pref("extensions.torlauncher.quickstart", true);
user_pref("general.autoScroll", true);
user_pref("mousewheel.default.delta_multiplier_x", 300);
user_pref("mousewheel.default.delta_multiplier_y", 300);
user_pref("privacy.prioritizeonions.enabled", true);
user_pref("privacy.prioritizeonions.showNotification", false);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("xpinstall.signatures.required", false);

// user_pref("extensions.torlauncher.control_port", 9161);
// user_pref("network.proxy.socks_port", 9160);
// user_pref("extensions.torlauncher.control_port", 9151);
// user_pref("network.proxy.socks_port", 9150);
user_pref("extensions.torlauncher.control_port", 9171);
user_pref("network.proxy.socks_port", 9170);
